//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectLeMoulin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.CategoryProduct = new HashSet<CategoryProduct>();
            this.Week = new HashSet<Week>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public bool TVQ { get; set; }
        public bool TPS { get; set; }
        public bool Avaibled { get; set; }
    
        public virtual ICollection<CategoryProduct> CategoryProduct { get; set; }
        public virtual ICollection<Week> Week { get; set; }
    }
}
