//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryProduct
    {
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public string detail { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Products Products { get; set; }
    }
}
