//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EpicerieEntities : DbContext
    {
        public EpicerieEntities()
            : base("name=EpicerieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AspNetUsers> AspNetUsers { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<CategoryProduct> CategoryProduct { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<Suppliers> Suppliers { get; set; }
        public DbSet<WeekProduct> WeekProduct { get; set; }
        public DbSet<Weeks> Weeks { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<OrderDetails> OrderDetails { get; set; }
        public DbSet<Tax> Taxes { get; set; }
    
        public virtual int CopyLastWeekProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CopyLastWeekProducts");
        }
    }
}
