//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        public int EventId { get; set; }
        public string TitleEvenement { get; set; }
        public string PrincipalPhotoEvenement { get; set; }
        public string PlaceEvenement { get; set; }
        public string AdresseEvenement { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.TimeSpan> HourStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public Nullable<System.TimeSpan> HourEnd { get; set; }
        public string Text { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Poublier { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
