//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public int PageID { get; set; }
        public string MenuName { get; set; }
        public string UserId { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public bool Principal { get; set; }
        public Nullable<int> SousMenu { get; set; }
        public Nullable<bool> Poublier { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
