//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public int PageID { get; set; }
        public string MenuName { get; set; }
        public string UserId { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public bool Principal { get; set; }
        public Nullable<int> SousMenu { get; set; }
        public Nullable<bool> Poublier { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
