//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.CategoryProduct = new HashSet<CategoryProduct>();
            this.WeekProduct = new HashSet<WeekProduct>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public bool TVQ { get; set; }
        public bool TPS { get; set; }
        public bool Avaibled { get; set; }
    
        public virtual ICollection<CategoryProduct> CategoryProduct { get; set; }
        public virtual ICollection<WeekProduct> WeekProduct { get; set; }
    }
}
