//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectLeMoulin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CategoryProducts = new HashSet<CategoryProduct>();
            this.Weeks = new HashSet<Week>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public bool TVQ { get; set; }
        public bool TPS { get; set; }
        public bool Avaibled { get; set; }
    
        public virtual ICollection<CategoryProduct> CategoryProducts { get; set; }
        public virtual ICollection<Week> Weeks { get; set; }
    }
}
