//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weeks
    {
        public Weeks()
        {
            this.WeekProduct = new HashSet<WeekProduct>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int WeekId { get; set; }
        public Nullable<System.DateTime> Date_Debut { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
        public Nullable<System.DateTime> Date_Recuperation { get; set; }
    
        public virtual ICollection<WeekProduct> WeekProduct { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
