//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekProduct
    {
        public WeekProduct()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int WeekId { get; set; }
        public int ProductId { get; set; }
        public int SupplierId { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public string Format { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Weeks Weeks { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
