//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectLeMoulin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Week
    {
        public Week()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public System.DateTime DateSemaine { get; set; }
        public int ProductId { get; set; }
        public int SupplierId { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public string Format { get; set; }
    
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual Products Products { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
